import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    APL: z.enum(["file", "dynamodb", "upstash"]).default("file"),
    APP_API_BASE_URL: z.string().optional(),
    APP_IFRAME_BASE_URL: z.string().optional(),
    FILE_APL_PATH: z.string().default(".data/apl.json"),
    DYNAMODB_MAIN_TABLE_NAME: z.string().optional(),
    AWS_REGION: z.string().optional(),
    AWS_ACCESS_KEY_ID: z.string().optional(),
    AWS_SECRET_ACCESS_KEY: z.string().optional(),
    // Saleor media storage (Cloudflare R2) — separate from Dynamo APL AWS_* keys
    MEDIA_S3_ENDPOINT_URL: z.string().optional(),
    MEDIA_S3_REGION_NAME: z.string().default("auto"),
    MEDIA_BUCKET_NAME: z.string().optional(),
    MEDIA_ACCESS_KEY_ID: z.string().optional(),
    MEDIA_SECRET_ACCESS_KEY: z.string().optional(),
    MEDIA_CUSTOM_DOMAIN: z.string().optional(),
    MAGIC_MEDIA_CATALOG_KEY: z.string().default("magic-media/magic-media.json"),
    MAGIC_MEDIA_UPLOAD_PREFIX: z.string().default("file_upload/"),
    MANIFEST_APP_ID: z.string().default("magic-cms.app"),
    PORT: z.coerce.number().default(3002),
    SECRET_KEY: z.string(),
  },
  runtimeEnv: {
    APL: process.env.APL,
    APP_API_BASE_URL: process.env.APP_API_BASE_URL,
    APP_IFRAME_BASE_URL: process.env.APP_IFRAME_BASE_URL,
    FILE_APL_PATH: process.env.FILE_APL_PATH,
    DYNAMODB_MAIN_TABLE_NAME: process.env.DYNAMODB_MAIN_TABLE_NAME,
    AWS_REGION: process.env.AWS_REGION,
    AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
    AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
    MEDIA_S3_ENDPOINT_URL: process.env.MEDIA_S3_ENDPOINT_URL || process.env.AWS_S3_ENDPOINT_URL,
    MEDIA_S3_REGION_NAME: process.env.MEDIA_S3_REGION_NAME || process.env.AWS_S3_REGION_NAME || "auto",
    MEDIA_BUCKET_NAME: process.env.MEDIA_BUCKET_NAME || process.env.AWS_MEDIA_BUCKET_NAME,
    MEDIA_ACCESS_KEY_ID: process.env.MEDIA_ACCESS_KEY_ID || process.env.R2_ACCESS_KEY_ID,
    MEDIA_SECRET_ACCESS_KEY: process.env.MEDIA_SECRET_ACCESS_KEY || process.env.R2_SECRET_ACCESS_KEY,
    MEDIA_CUSTOM_DOMAIN: process.env.MEDIA_CUSTOM_DOMAIN || process.env.AWS_MEDIA_CUSTOM_DOMAIN,
    MAGIC_MEDIA_CATALOG_KEY: process.env.MAGIC_MEDIA_CATALOG_KEY,
    MAGIC_MEDIA_UPLOAD_PREFIX: process.env.MAGIC_MEDIA_UPLOAD_PREFIX,
    MANIFEST_APP_ID: process.env.MANIFEST_APP_ID,
    PORT: process.env.PORT,
    SECRET_KEY: process.env.SECRET_KEY,
  },
  isServer: typeof window === "undefined",
});
